services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    restart: unless-stopped

    ports:
      - "1883:1883"
      - "9001:9001"

    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  mqtt-explorer:
    image: ruseler/mqtt-explorer:local
    container_name: mqtt-explorer
    restart: unless-stopped
    ports:
      - "3001:3000"

    environment:
      MQTT_EXPLORER_SKIP_AUTH: "true"
      MQTT_AUTO_CONNECT_HOST: mosquitto
      MQTT_AUTO_CONNECT_PORT: "1883"

    volumes:
      - ./mqtt-explorer/data:/app/data
    depends_on:
      - mosquitto
